---
include:
  - project: "hc/ops/ci"
    file: "k8s/release.yml"

stages:
  - test
  - E2E
  - build
  - release

variables:
  GOPROXY: goproxy.prodext.hcinfra.de
  GONOSUMDB: hetzner.cloud

unit:
  image: golang:1.15
  stage: test
  script:
    - go test $(go list ./... | grep -v e2etests) -v
  tags:
    - hc-bladerunner

.k8se2e: &k8se2e
  image: docker:git
  stage: E2E
  variables:
    K8S_VERSION: 1.17.14
  before_script:
    - apk add --no-cache git make musl-dev go
  script:
    - go test $(go list ./... | grep e2etests) -v -timeout 60m
  tags:
    - hc-bladerunner-build

k8s 1.17:
  <<: *k8se2e
  variables:
    K8S_VERSION: 1.17.14

k8s 1.18:
  <<: *k8se2e
  variables:
    K8S_VERSION: 1.18.12

k8s 1.19:
  <<: *k8se2e
  variables:
    K8S_VERSION: 1.19.4

k8s 1.20:
  <<: *k8se2e
  variables:
    K8S_VERSION: 1.20.0
