apiVersion: v1
kind: ServiceAccount
metadata:
  name: hcloud-csi
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcloud-csi
rules:
# attacher
- apiGroups: [""]
  resources: [persistentvolumes]
  verbs: [get, list, watch, update, patch]
- apiGroups: [""]
  resources: [nodes]
  verbs: [get, list, watch]
- apiGroups: [csi.storage.k8s.io]
  resources: [csinodeinfos]
  verbs: [get, list, watch]
- apiGroups: [storage.k8s.io]
  resources: [csinodes]
  verbs: [get, list, watch]
- apiGroups: [storage.k8s.io]
  resources: [volumeattachments]
  verbs: [get, list, watch, update, patch]
- apiGroups: [storage.k8s.io]
  resources: [volumeattachments/status]
  verbs: [patch]
# provisioner
- apiGroups: [""]
  resources: [secrets]
  verbs: [get, list]
- apiGroups: [""]
  resources: [persistentvolumes]
  verbs: [get, list, watch, create, delete, patch]
- apiGroups: [""]
  resources: [persistentvolumeclaims, persistentvolumeclaims/status]
  verbs: [get, list, watch, update, patch]
- apiGroups: [storage.k8s.io]
  resources: [storageclasses]
  verbs: [get, list, watch]
- apiGroups: [""]
  resources: [events]
  verbs: [list, watch, create, update, patch]
- apiGroups: [snapshot.storage.k8s.io]
  resources: [volumesnapshots]
  verbs: [get, list]
- apiGroups: [snapshot.storage.k8s.io]
  resources: [volumesnapshotcontents]
  verbs: [get, list]
# resizer
- apiGroups: [""]
  resources: [pods]
  verbs: [get, list, watch]
# node
- apiGroups: [""]
  resources: [events]
  verbs: [get, list, watch, create, update, patch]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcloud-csi
subjects:
- kind: ServiceAccount
  name: hcloud-csi
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: hcloud-csi
  apiGroup: rbac.authorization.k8s.io
