{{- if .Values.storageClasses }}
{{- range $key, $val := .Values.storageClasses }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ $val.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ $val.defaultStorageClass | default "false" | quote }}
provisioner: csi.hetzner.cloud
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: {{ $val.reclaimPolicy | quote }}
{{- if $val.allowedTopologyCloudServer }}
allowedTopologies:
- matchLabelExpressions:
  - key: instance.hetzner.cloud/is-root-server
    values:
    - "false"
- matchLabelExpressions:
  - key: instance.hetzner.cloud/provided-by
    values:
    - "cloud"
{{- end }}
---
{{- end }}
{{- end }}